### PR TITLE
Update MainModule.lua

### PR DESCRIPTION
**Pull request by J-Man775**
For people who want to get the last status of services that is known.

### CODE REVIEW

**Comment by FxllenCode** [comment]
Amazing! This will definitely work in the meantime, I'm gonna put this as a separate branch form the time being as the upptime-latest.json update will be much more efficient. Give me a couple of hours so I can confirm this works! :grin:

**Review by FxllenCode — APPROVED** [review]
This is awesome! Thank you for your contribution. I will be merging these changes. I'll be giving you a contributor rank is our discord server and you'll also have get that rank in our Roblox group. I'll make sure to credit you while we use these updates. I'll get working on Docs on examples, thanks again! 🙂

**Comment by J-Man775** [comment]
> This is awesome! Thank you for your contribution. I will be merging these changes. I'll be giving you a contributor rank is our discord server and you'll also have get that rank in our Roblox group. I'll make sure to credit you while we use these updates. I'll get working on Docs on examples, thanks again! 🙂

Can't wait for the live status system! I joined the Status+ group. I am pretty sure to come back and contribute again when the live status system works :D

**Comment by FxllenCode** [comment]
Sounds good! This works but upptime is working on creating a better solution to this which will make this a lot simpler and more efficient. Great work!

How did you find us? :grin:

**Comment by J-Man775** [comment]
> Sounds good! This works but upptime is working on creating a better solution to this which will make this a lot simpler and more efficient. Great work!
> 
> How did you find us? 😁

the ROBLOX DevForum of course 😄

**Comment by J-Man775** [comment]
Hey! Unfortunate your DM's on Discord are closed. Can you please fix the webhook in the server? It works but doesn't publish it to servers following that channel.

**Comment by FxllenCode** [comment]
I fixed that, recently. It should work now!

**Pull request merged**
